# Generated by Django 2.1.1 on 2018-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('to_user_id', models.IntegerField(blank=True, null=True)),
                ('gen_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
