# Generated by Django 2.1.1 on 2018-09-21 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=20, verbose_name='email')),
                ('dep', models.CharField(blank=True, max_length=46, verbose_name='department')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='telephone')),
                ('sex', models.CharField(blank=True, max_length=4, verbose_name='sex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
