# Generated by Django 2.1.1 on 2019-04-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0002_delete_assets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={},
        ),
    ]
