# Generated by Django 2.1.2 on 2019-04-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0003_auto_20190408_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': 'IDC机房', 'verbose_name_plural': 'IDC机房'},
        ),
    ]
