XXXXXXXXX XXXXX
XXXXXX
  XXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
      XXXXX
    XXXXXX

    XXXXXXXXX
      XXXXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
XX
 X XXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX
 X XXXXXXXXXX XXX XXXXXX XXXXXXXXX XXXX XXXX XXXXXXX XXXX XXXXXXXX XXXXX XXXXXX
 XX

XXXXX
  X XXXXXXXX

XXXXXXXX
  X XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX X XXXXXX XXXX X XXXXXX X
  X XXXXXXXXXXXXXX

XXXXXXXXXXXXXX
  X XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX X XXXXXX XXXX X XXXXXX X
  X XXXXXXX

XXXXXXX
  X XXXXXXX
  X XXX XXXXXXXXXXXXXXXXX XXX X XXXXXX XXXXXXXXX X

XXXXXXX XXXXXXXXX
  X XXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX X

XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXX XXXXXX XXXXXXXXX
          XXXXXXXXXXXX XXXX
        XXX
      XXXXXXXXX
      XXXXXXX XXXXXX XXXXXXXXX
      XXX XXXXXXX XX XXXXXX XXXXXXXXXXXXX
    XXXXXXXXXX
  XXXXXXX
XXXXXXX
