# Generated by Django 2.1.2 on 2019-03-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('server', '物理机'), ('server', '虚拟机')], default='server', max_length=64, verbose_name='资产类型')),
                ('hostname', models.CharField(max_length=32, unique=True)),
                ('idc', models.CharField(max_length=32, unique=True, verbose_name='机房')),
                ('tel_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='电信IP')),
                ('uni_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='联通IP')),
                ('mob_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='移动IP')),
                ('internal_ip', models.GenericIPAddressField(verbose_name='内网IP')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU 型号')),
                ('cpu_count', models.CharField(max_length=32, null=True, verbose_name='CPU 逻辑个数')),
                ('mem_total', models.CharField(blank=True, max_length=64, null=True, verbose_name='总内存MB')),
                ('os', models.CharField(blank=True, max_length=128, null=True, verbose_name='操作系统')),
                ('os_version', models.CharField(blank=True, max_length=16, null=True, verbose_name='os版本')),
                ('salt_state', models.TextField(blank=True, verbose_name='salt状态')),
                ('asset_state', models.CharField(choices=[('ok', 'ok'), ('repair', 'repair'), ('withdraw', 'withdraw')], default='ok', max_length=128, verbose_name='主机状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '主机信息',
            },
        ),
    ]
