XXXXXXXXX XXXXX

XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
      XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
      X
    XXXXXXXX
XXXX XXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXX
XXXXXX

XXXXXXXXX
XXXXXXXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX    
XXXXXXXXXXXXX     XXXXXXXXXXXXXX     XXXXXXXXXXXX X
XXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX     XXXXXXXX X
XXXXXXXX          XXXXXXXXXXXXXX     XXXXXXXX XXXXXXX X
XXXXXXXX          XXXXXXXXXXXXXX     XXXXXXXX XXXXXXXXXXXXXXXXX X
XXXXXXXXXXX
XXXXXXX

    XXXXXXXX
      XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
    XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX
