XXXXXXXXX XXXXX

XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXXXX
XXXX XXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXX
XXXXXX

XXXXXXXXX
XXXXXXX XXXXXXXXX
XXXXXX
XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
XXXXXXX XXXXXXX
XXXXXXX XXXX

XX 
 X  X
 X  XXXXXXXXXX
 X  XXXXXXXX
 XX

X X XXXXXX XXXX XXXXXXXX

XXXXX
        XXXX    XXXX XXX
        XXX     XXX XXXXXXXX
        XX      XXXX
        XXX     XXX XX
        XXX     XXXX XXX

XXXXXXXX
        XXXXXX XXXXXX XXXXXXXXX XXX
XXXXXXXXXXX
        XXXXXXX

        XXXXXXXX
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXX XXXXX
                XXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXX
            XXX
        XXXXXXXXX

        XXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXX
        XXX XXX XXXXXXXXX XXXXX XXXXXXXX
        XX XXXXX X XXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX XX XXX XX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXX XXXXXXXXX XXXX XXXXXX XXX XXX XXXXXXXXX XXX XXXXXXX
        XXXXXXXXXX XXX XXX XXXXXXXX XXXXXXXXXXXXX

        XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
