XXXXXXXXX XXXXX

XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
XXXX XXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXX
XXXXXX

XXXXXXXXX
XXXXXXXXXX XXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX

B BBB BBBB BB BB B
  XXXXXXXXXXXXXXXXXXXXX
BBBBBB B


BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
  BBBBBB
BBBBB

XX XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXX
  XX
XX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXXXXXXXXXX
    XXXXXXXX
      XXX XXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXX
    XXXXXXXXX
  XXXXXXXXXX
